import { Category, Account, Transaction, FinancialGoal } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  // Despesas
  { id: 'cat-moradia', name: 'Moradia & Contas', type: 'expense', color: '#6366F1', iconName: 'Home', budgetMonthly: 2800 },
  { id: 'cat-alimentacao', name: 'Alimentação & Supermercado', type: 'expense', color: '#F59E0B', iconName: 'Utensils', budgetMonthly: 1600 },
  { id: 'cat-transporte', name: 'Transporte & Combustível', type: 'expense', color: '#3B82F6', iconName: 'Car', budgetMonthly: 750 },
  { id: 'cat-saude', name: 'Saúde & Cuidados', type: 'expense', color: '#EC4899', iconName: 'HeartPulse', budgetMonthly: 600 },
  { id: 'cat-lazer', name: 'Lazer & Restaurantes', type: 'expense', color: '#8B5CF6', iconName: 'Sparkles', budgetMonthly: 800 },
  { id: 'cat-educacao', name: 'Educação & Livros', type: 'expense', color: '#10B981', iconName: 'GraduationCap', budgetMonthly: 400 },
  { id: 'cat-assinaturas', name: 'Assinaturas & Serviços', type: 'expense', color: '#06B6D4', iconName: 'Tv', budgetMonthly: 250 },
  { id: 'cat-outros-desp', name: 'Outras Despesas', type: 'expense', color: '#64748B', iconName: 'Layers', budgetMonthly: 500 },

  // Receitas
  { id: 'cat-salario', name: 'Salário & Pró-labore', type: 'income', color: '#10B981', iconName: 'Briefcase' },
  { id: 'cat-freelance', name: 'Freelance & Projetos', type: 'income', color: '#059669', iconName: 'Laptop' },
  { id: 'cat-investimentos', name: 'Rendimentos & Dividendos', type: 'income', color: '#0D9488', iconName: 'TrendingUp' },
  { id: 'cat-outros-rec', name: 'Outras Receitas', type: 'income', color: '#14B8A6', iconName: 'CircleDollarSign' },
];

export const INITIAL_ACCOUNTS: Account[] = [
  { id: 'acc-nubank', name: 'Conta Digital Nubank', institution: 'Nubank', type: 'checking', balance: 5420.50, color: '#820AD1', iconName: 'Landmark' },
  { id: 'acc-itau', name: 'Itaú Personalité', institution: 'Itaú', type: 'checking', balance: 9380.00, color: '#EC7000', iconName: 'Building2' },
  { id: 'acc-cartao', name: 'Cartão de Crédito Black', institution: 'Mastercard Black', type: 'credit', balance: -2450.30, color: '#1E293B', iconName: 'CreditCard' },
  { id: 'acc-reserva', name: 'Reserva Selic (100% CDI)', institution: 'Tesouro Direto', type: 'savings', balance: 28500.00, color: '#059669', iconName: 'ShieldCheck' },
  { id: 'acc-carteira', name: 'Carteira (Dinheiro Físico)', institution: 'Espécie', type: 'cash', balance: 350.00, color: '#64748B', iconName: 'Wallet' },
];

export const INITIAL_GOALS: FinancialGoal[] = [
  { id: 'goal-1', title: 'Reserva de Emergência (6 Meses)', targetAmount: 35000, currentAmount: 28500, deadline: '2026-12-31', category: 'Segurança', color: '#10B981' },
  { id: 'goal-2', title: 'Viagem de Férias para a Europa', targetAmount: 18000, currentAmount: 11200, deadline: '2027-04-15', category: 'Viagem', color: '#3B82F6' },
  { id: 'goal-3', title: 'Novo Setup de Trabalho / MacBook', targetAmount: 12000, currentAmount: 8400, deadline: '2026-11-30', category: 'Equipamento', color: '#8B5CF6' },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    description: 'Salário Mensal - Empresa Tech',
    amount: 11500.00,
    type: 'income',
    category: 'cat-salario',
    date: '2026-09-05',
    status: 'paid',
    accountId: 'acc-itau',
    paymentMethod: 'Transferência',
    notes: 'Depósito integral do salário CLT',
    createdAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'tx-2',
    description: 'Projeto UI/UX Design - Landing Page',
    amount: 3200.00,
    type: 'income',
    category: 'cat-freelance',
    date: '2026-09-10',
    status: 'paid',
    accountId: 'acc-nubank',
    paymentMethod: 'Pix',
    notes: 'Entrega final da consultoria de produto',
    createdAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'tx-3',
    description: 'Dividendos FIIs & Ações',
    amount: 485.60,
    type: 'income',
    category: 'cat-investimentos',
    date: '2026-09-15',
    status: 'paid',
    accountId: 'acc-reserva',
    paymentMethod: 'Transferência',
    notes: 'Rendimento mensal automático da carteira',
    createdAt: '2026-09-15T08:00:00Z',
  },
  {
    id: 'tx-4',
    description: 'Aluguel do Apartamento + Condomínio',
    amount: 2650.00,
    type: 'expense',
    category: 'cat-moradia',
    date: '2026-09-08',
    status: 'paid',
    accountId: 'acc-itau',
    paymentMethod: 'Boleto',
    notes: 'Vencimento todo dia 10',
    createdAt: '2026-09-08T10:15:00Z',
  },
  {
    id: 'tx-5',
    description: 'Supermercado Pão de Açúcar (Compras do Mês)',
    amount: 890.40,
    type: 'expense',
    category: 'cat-alimentacao',
    date: '2026-09-07',
    status: 'paid',
    accountId: 'acc-cartao',
    paymentMethod: 'Cartão',
    notes: 'Hortifruti, proteínas e limpeza',
    createdAt: '2026-09-07T18:20:00Z',
  },
  {
    id: 'tx-6',
    description: 'Conta de Energia Elétrica (Enel)',
    amount: 215.80,
    type: 'expense',
    category: 'cat-moradia',
    date: '2026-09-12',
    status: 'paid',
    accountId: 'acc-nubank',
    paymentMethod: 'Pix',
    notes: 'Consumo do mês anterior',
    createdAt: '2026-09-12T11:00:00Z',
  },
  {
    id: 'tx-7',
    description: 'Combustível Posto Shell (Gasolina V-Power)',
    amount: 260.00,
    type: 'expense',
    category: 'cat-transporte',
    date: '2026-09-11',
    status: 'paid',
    accountId: 'acc-cartao',
    paymentMethod: 'Cartão',
    notes: 'Tanque cheio',
    createdAt: '2026-09-11T16:45:00Z',
  },
  {
    id: 'tx-8',
    description: 'Jantar com Amigos - Restaurante Italiano',
    amount: 240.00,
    type: 'expense',
    category: 'cat-lazer',
    date: '2026-09-13',
    status: 'paid',
    accountId: 'acc-cartao',
    paymentMethod: 'Cartão',
    notes: 'Comemoração de aniversário',
    createdAt: '2026-09-13T21:30:00Z',
  },
  {
    id: 'tx-9',
    description: 'Internet Fibra Óptica 500 Mega',
    amount: 129.90,
    type: 'expense',
    category: 'cat-moradia',
    date: '2026-09-14',
    status: 'paid',
    accountId: 'acc-nubank',
    paymentMethod: 'Pix',
    createdAt: '2026-09-14T09:10:00Z',
  },
  {
    id: 'tx-10',
    description: 'Mensalidade Academia SmartFit',
    amount: 139.90,
    type: 'expense',
    category: 'cat-saude',
    date: '2026-09-15',
    status: 'paid',
    accountId: 'acc-cartao',
    paymentMethod: 'Cartão',
    createdAt: '2026-09-15T07:30:00Z',
  },
  {
    id: 'tx-11',
    description: 'Assinatura Claude Pro + Spotify Familiar',
    amount: 145.00,
    type: 'expense',
    category: 'cat-assinaturas',
    date: '2026-09-18',
    status: 'pending',
    accountId: 'acc-cartao',
    paymentMethod: 'Cartão',
    notes: 'Cobrança recorrente no cartão de crédito',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'tx-12',
    description: 'Consultoria de Design Sprint - Parcela 2',
    amount: 2500.00,
    type: 'income',
    category: 'cat-freelance',
    date: '2026-09-22',
    status: 'pending',
    accountId: 'acc-nubank',
    paymentMethod: 'Pix',
    notes: 'Previsto para cair no dia 22',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'tx-13',
    description: 'Fatura do Cartão de Crédito Itaú Black',
    amount: 850.00,
    type: 'expense',
    category: 'cat-outros-desp',
    date: '2026-09-25',
    status: 'pending',
    accountId: 'acc-itau',
    paymentMethod: 'Boleto',
    notes: 'Fechamento da fatura parcial',
    createdAt: '2026-09-01T00:00:00Z',
  }
];
